// Generated by tools\generate-browser-config.ps1 from config\local.json -
// do not hand-edit, re-run the script instead. See config.example.js for
// why these values (url + anon key) are safe to ship to the browser.
window.TUNA_BROWSER_CONFIG = {
  configured: true,
  url: 'https://ywphthybzklkqajkbbeg.supabase.co',
  anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3cGh0aHliemtsa3FhamtiYmVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAwOTE3NzAsImV4cCI6MjEwNTY2Nzc3MH0.YPNrs8A6yTJHLys5b28Wo_FNVy73XwL-Re4gbbWOQW4',
};
